In [25]:
import time

import pandas as pd
import numpy as np

from treesampling.algorithms.castaway_reboot import Castaway2RST

In [26]:
# dat = pd.read_csv('/Users/zemp/PycharmProjects/treesampling/experiments/20250409135146_FINAL.csv')
dat = pd.read_csv('/Users/zemp/PycharmProjects/treesampling/experiments/tet20250409141334_feas.csv')
dat.head()

,low_weight,n_nodes,seed,wilson_time,kulkarni_time,castaway_time,n_sample,num_components,wilson_edge_marg_mse,kulkarni_edge_marg_mse,...,cheegers_const,tot_weight,log_det,wilson_tot_weight_diff,kulkarni_tot_weight_diff,castaway_tot_weight_diff,crasher_issue,wilson_pmass_covered,kulkarni_pmass_covered,castaway_pmass_covered
0,-2,7,0,1.041528,2.464282,3.833359,1000,2,0.001562,0.001506,...,-0.515922,-2.024280,-2.023698,-1.007261,-0.994322,-1.004360,0,0.365005,0.369759,0.366066
1,-2,7,1,1.086371,2.547220,3.813897,1000,2,0.001613,0.001530,...,-0.514118,-2.076770,-2.076250,-0.955188,-0.979919,-0.978315,0,0.384540,0.375146,0.375749
2,-2,7,2,1.084443,2.531497,3.887697,1000,2,0.001531,0.001444,...,-0.522336,-2.067762,-2.067225,-0.947483,-0.989791,-1.040743,0,0.387508,0.371455,0.353003
3,-2,7,3,1.058200,2.339925,3.878471,1000,2,0.001600,0.001519,...,-0.529086,-2.022205,-2.021662,-0.982256,-1.024824,-1.005887,0,0.374262,0.358665,0.365521
4,-2,7,4,1.156339,2.342376,4.048285,1000,2,0.001523,0.001629,...,-0.521449,-1.999199,-1.998659,-0.996842,-0.992794,-1.015644,0,0.368844,0.370340,0.361974

In [35]:
# get table | low_weight (log)   | conductance | wilson time | kulkarni edge_freq_mse | castaway edge_freq_mse | crasher |

agg_tab = dat.groupby('low_weight').agg({
    'j_conductance': 'mean',
    # 'wilson_time': 'mean',
    # 'kulkarni_time': 'mean',
    # 'castaway_time': 'mean',
    'wilson_edge_marg_mse': 'mean',
    'kulkarni_edge_marg_mse': 'mean',
    'castaway_edge_marg_mse': 'mean',
    'wilson_edge_cooccurrence_mse': 'mean',
    'kulkarni_edge_cooccurrence_mse': 'mean',
    'castaway_edge_cooccurrence_mse': 'mean',
    'wilson_pmass_covered': 'mean',
    'kulkarni_pmass_covered': 'mean',
    'castaway_pmass_covered': 'mean',
    # 'wilson_marginals_kl': 'mean',
    # 'kulkarni_marginals_kl': 'mean',
    # 'castaway_marginals_kl': 'mean',
    # 'wilson_cooccurrence_kl': 'mean',
    # 'kulkarni_cooccurrence_kl': 'mean',
    # 'castaway_cooccurrence_kl': 'mean',
    'crasher_issue': 'mean'
    # 'wilson_tot_weight_diff': 'mean',
    # 'kulkarni_tot_weight_diff': 'mean',
    # 'castaway_tot_weight_diff': 'mean',
}).reset_index()
pd.options.display.float_format = "{:,.2g}".format
agg_tab.sort_values('low_weight', ascending=False, inplace=True)
agg_tab = agg_tab[agg_tab['low_weight'] != -50]
agg_tab.head(10)

,low_weight,j_conductance,wilson_edge_marg_mse,kulkarni_edge_marg_mse,castaway_edge_marg_mse,wilson_edge_cooccurrence_mse,kulkarni_edge_cooccurrence_mse,castaway_edge_cooccurrence_mse,wilson_pmass_covered,kulkarni_pmass_covered,castaway_pmass_covered,crasher_issue
9,-2,-1.4,0.0015,0.0015,0.0015,0.0006,0.0006,0.0006,0.37,0.36,0.37,0
8,-3,-2.2,0.00046,0.00047,0.00047,0.00021,0.00021,0.00021,0.65,0.65,0.65,0
7,-5,-3.9,2.3e-05,2.4e-05,2.1e-05,1.2e-05,1.3e-05,1.1e-05,0.92,0.91,0.92,0
6,-7,-5.8,6.9e-06,6.9e-06,7.8e-06,3.8e-06,3.8e-06,4.4e-06,0.98,0.97,0.97,0
5,-10,-8.5,NaN,8e-06,6e-06,NaN,4.1e-06,3.3e-06,NaN,0.98,0.98,0
4,-20,-18,NaN,2e-05,1.7e-05,NaN,9.1e-06,8e-06,NaN,0.97,0.97,0
3,-30,-27,NaN,3.1e-05,0.00012,NaN,1.4e-05,5.9e-05,NaN,0.96,0.9,1
2,-40,-36,NaN,0.0026,0.00012,NaN,0.0011,5.8e-05,NaN,0.78,0.91,1
0,-100,-91,NaN,NaN,3.5e-05,NaN,NaN,2.1e-05,NaN,NaN,0.96,1

In [24]:
# read time data
time_data = pd.read_csv('/Users/zemp/PycharmProjects/treesampling/experiments/20250409145847_time.csv')
time_data.head(20)

,k,seed,log_eps,wilson_time,kulkarni_time,castaway_time,trick,crashers
0,7,0,-1,0.000600,0.001280,0.001685,1,0
1,7,1,-1,0.000317,0.001103,0.001640,1,0
2,7,2,-1,0.000306,0.001102,0.001660,1,0
3,7,3,-1,0.000344,0.001487,0.002319,1,0
4,7,4,-1,0.000351,0.001046,0.001646,1,0
5,7,5,-1,0.000315,0.001059,0.001649,1,0
6,7,6,-1,0.000318,0.001074,0.001634,1,0
7,7,7,-1,0.000315,0.001010,0.002382,1,0
8,7,8,-1,0.000421,0.001255,0.001641,1,0
9,7,9,-1,0.000314,0.001102,0.001637,1,0
10,7,0,-2,0.000408,0.000902,0.001616,1,0
11,7,1,-2,0.000440,0.000928,0.001620,1,0
12,7,2,-2,0.000431,0.000935,0.001619,1,0
13,7,3,-2,0.000417,0.000861,0.001615,1,0
14,7,4,-2,0.000418,0.000822,0.001622,1,0
15,7,5,-2,0.000423,0.000902,0.001640,1,0
16,7,6,-2,0.000442,0.000923,0.001623,1,0
17,7,7,-2,0.000412,0.000820,0.001620,1,0
18,7,8,-2,0.000413,0.000888,0.001621,1,0
19,7,9,-2,0.000408,0.000955,0.001627,1,0

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid", palette='colorblind')